### PR TITLE
A simple update sql generator for linux

### PR DESCRIPTION
**Pull request by fzerorubigd**
A simple script to create update sql base on last reference. with this script there is no need to track update files manually. this script create an update sql base on your last time you use this script.

### CODE REVIEW

**Comment by DDuarte** [comment]
Interesting script, thanks.

I think you misspelled reference and it seems that it does not handle changed SQL files (it shouldn't happen but it is a possibility)

**Comment by fzerorubigd** [comment]
I found that I misspelled reference every where in script, but I want to find only new scripts since updated scripts are not my interest. every new script after a commit (some check point) is my interest.

**Comment by DDuarte** [comment]
Imagine that an sql is pushed to repository with syntax errors and then I run your script and one hour later a commit fixing the errors in previous sql gets into the repo. How would your script handle that?

**Comment by fzerorubigd** [comment]
If both change are after the check-point its ok (Script found a new sql and then simply fetch the current copy which is fixed by the way) 
But if sql added before check-point and some one update that after using this script the script can not find that.

I know its a hard job to maintain such a database (I have a job like this with a 1GB db of wrecked cars info and I hate that :) ) but I can suggest a way, if you fix a file, simply rename it. then every thing is OK :)

**Comment by DDuarte** [comment]
Could you fix the typo? refrence -> reference?

**Comment by fzerorubigd** [comment]
Sorry for delay. its fixed. and now I see i have typo in last commit message :)))) typo not type!!!

**Comment by DDuarte** [comment]
Still missing some changes: .gitignore line 1, auto_merge.sh lines 4, 5 and 6

Squash the commits into one, please

**Pull request merged**
