### PR TITLE
DB/LFG: add item level requirement for all Cataclysm dungeons

### PR DESCRIPTION
**Pull request by ghost**
Data source: http://wowpedia.org/Dungeon_Finder#section_6
display ingame won't work due to issue: https://github.com/TrinityCore/TrinityCore/issues/12456

Shadowfang Keep and Deadmines will be added in a seperate pul request.

### CODE REVIEW

**Comment by Aokromes** [comment]
Anyway, for SQL only small fixes better simply a ticket.

**Comment by ghost** [comment]
@Aokromes if you took a look at the query u will see that the non-heroic dungeons have different itemlevel requirements. so you cant compress them into a simgle query

**Comment by Aokromes** [comment]
Ups i mistaked 4 xd but still better  6 than your way :P

**Comment by Aokromes** [comment]
It needs to be updated after bb7233b

**Pull request closed without merging**
