### PR TITLE
Fixed uldum creatures with the first letter of the name 'B'.

### PR DESCRIPTION
**Pull request by spycheast**

### CODE REVIEW

**Comment by DDuarte** [comment]
Don't assign custom gossip_menu_ids nor factions

If you have multiple spawns inserts, use a single "INSERT INTO" query

**Comment by spycheast** [comment]
How can I get gossip_menu_id? Sniffer is not public(I'm not trying to say "give it to me coz I'm helping" or sth like that). The text is offlike, just id is not (can be easily corrected after sb sniffs that gossip). It seems that ids give no errors and gossips work as should.
As to the spawns and single query... Currently, my structure includes "-- npcname" then all features, which need correction(faction 14 instead of friendly 35 is not custom for me). If I will include all spawns to one query that will "broke" the structure, but if you insist on doing this, I will...

**Comment by DDuarte** [comment]
There was a public snifferin 4.3.4 but so far no one did one for 5.x

About the spawns, it's really better keeping everything in the same insert query

Thanks for everything

**Comment by spycheast** [comment]
Will wait for 5.x sniffer and as for spawns - ok, i will)

**Pull request closed without merging**
