### PR TITLE
DB/SAI: added Kezan zone scripts

### PR DESCRIPTION
**Pull request by cooler-SAI**
Most scripts added. I know that commits not a TC standart, but this scripts works good. may be someone wanna edit commits. Hope this will be usefull for 4.3.4/ Thanks anyway

### CODE REVIEW

**Comment by cooler-SAI** [comment]
all other scripts here https://github.com/cooler-SAI/patch - you can use all of them. almost all 4.3.4 content scripted there ( spells casts). more then 6588+ Entryes finished

**Comment by emptyus** [comment]
Dude, I've been following your work on your repo, it is amazing amount of time you spent on these scripts, and for me as a nooby it is great source for learning. I am sure TC will recognize it as a good help and reference for what they are about to do, even if it doesnt fit the standards. Great starting point to get things going at a faster pace toward a goal we all hope to see! I'd really hate if it would, by some miracle, not get much needed love and corrections :P Hopfuly you will get onto this DB boat soon, Malcrom needs halp!

**Comment by cooler-SAI** [comment]
so, add this cast spells for NPC's with Quests. my main work was on spells, not Quests in SAI. If NPC not have it - just add and enjoy. all Blizzlike, not a fun scripts. 
I don't have time for edit TC commit standart in all my scripts, just can help giving all my 3 years SAI 4.3.4 hard work for  free . My opinion - this can help a lot!
thanks,@emptyus  ))))

**Comment by DDuarte** [comment]
I know I'm a little bit late but thanks for these tons of fixes, @cooler-SAI

We have agreed to use your fixes as base however we'll need to rewrite some of them (comments, CMC, broadcast_texts and some other minor details).
We'll be adding these fixes to https://github.com/TrinityCore/TrinityCore/tree/6.x over the next couple of weeks. Maybe you'd like to help with the rewrite (with @Rushor and @Killyana)?  Join us at #trinity @ irc.rizon.net :+1:

**Comment by emptyus** [comment]
There you go Andrey, I knew this would happen! Great work right here! :+1:

**Pull request closed without merging**
