### PR TITLE
Updated skinning_loot_template and pickpocketing_loot_template with correct values.

### PR DESCRIPTION
**Pull request by Nefarion**
This includes Herbalism loot, Skinning loot, Pickpocketing loot, Engineering loot and Mining loot.

Treshold set to 2,5% (eg. tables from www.wowhead.com/npc=683 and www.wowhead.com/npc=688 have been merged.)
Created 508 Skinning entries with 1726 Items.
Created 117 Herbalism entries with 1360 Items.
Created 70 Mining entries with 362 Items.
Created 37 Engineering entries with 248 Items.
Created 2424 Pickpocketing entries with 13927 Items.
Updated total of 46627 creature_template entries.

### CODE REVIEW

**Comment by cooler-SAI** [comment]
awesome job

**Comment by ghost** [comment]
Looks like you've done alot :)

**Comment by Nefarion** [comment]
thanks, but there is a huge chunk missing, and parts are incorrect, thats why Kinzcool (i told him that already) and the others have not merged this till now :)

**Comment by soulfrost** [comment]
really good job man, thak u

**Comment by ZxBiohazardZx** [comment]
ripped from wowhead? some % make no sense. i always objected against using non-round numbers, the "blind draw with the parameters"  will always get you some delta% 

fix the stupid fake accuracy shit and get the templates closer. all you need to do is find mobs that share loot

example:

-- Created By: Slaverjaw(39185)
-- Used for: 46859,46860,46861,10990,39185,44694,42044,44573,
(@LootTemplate1 + 13, 4304, 68.04124, @SkinningLoot), -- Thick Leather
(@LootTemplate1 + 13, 8170, 25.7732, @SkinningLoot), -- Rugged Leather
(@LootTemplate1 + 13, 8169, 3.092783, @SkinningLoot), -- Thick Hide

-- Created By: Hellgazer(39186)
-- Used for: 39186,46938,
(@LootTemplate1 + 14, 4304, 70.72072, @SkinningLoot), -- Thick Leather
(@LootTemplate1 + 14, 8170, 24.32433, @SkinningLoot), -- Rugged Leather
(@LootTemplate1 + 14, 8169, 3.603604, @SkinningLoot), -- Thick Hide

these are the same template

the db %'s are 70, 25, 5, the select wowhead makes will balance it up

and there is alot more shit like that

**Pull request closed without merging**
