### PR TITLE
fix mistake

### PR DESCRIPTION
**Pull request by msoky**
`source_type` must be 9 timed actionlist

### CODE REVIEW

**Comment by Aokromes** [comment]
You really think someone will dig on old/updates_01 directory and apply that file?

**Comment by msoky** [comment]
i pointed out, that this is mistake..if you want, create new file...event cant run

**Comment by DDuarte** [comment]
@Aokromes: so bm...

@msoky: we can't edit old sql files so please create a new .sql file with update queries. thanks!

**Comment by msoky** [comment]
ok :)

**Pull request closed without merging**
