### PR TITLE
DB/Vendors: fixed tier 11 vendor for orgrimmar and stormwind

### PR DESCRIPTION
**Pull request by ghost**
As the title says. Here is a ordered completed T11 Vendor entry for both vendors ins orgrimmar and stormwind

### CODE REVIEW

**Comment by cooler-SAI** [comment]
good! waiting for Project wake up

**Comment by Kylroi** [comment]
Instead of having the exact same vendor list in the database twice, why not make a single reference entry and then point to it for each vendor?

**Comment by Exodius** [comment]
AFAIK, `npc_vendor` does not have a reference table. At least I never saw anyone using such a thing. Not even TC crew.

**Comment by Kylroi** [comment]
Fair enough. I just know that it's preferred to use a reference template if something is used more than once. With loot_template and npc_trainer supporting reference entries, it just seemed logical that npc_vendor should, too. If not, then a lack of vision was certainly behind the development of the table implementation. It certainly wouldn't be difficult to implement, though.

**Comment by Exodius** [comment]
@Kylroi, I hope you don't mind...
http://www.trinitycore.org/f/topic/9650-reference-table-for-npc-vendor-table/

**Comment by Kylroi** [comment]
Not at all. I see that you agree it just makes sense, since those other tables support references. Keep a uniform concept in the project.

**Comment by ghost** [comment]
That's why i decidied to keep it like it is.

**Comment by Kylroi** [comment]
@NorthStrider Actually, I'm surprised you didn't submit a patch that adds reference support for the npc_vendor table.

**Comment by ghost** [comment]
yes, because i dont see any reason to do that. this vendors are a unique case so i dont care about references.

**Comment by Kylroi** [comment]
Ah, but other vendors do exist that share the same or mostly the same vendor data with each other (i.e. reagent vendors and profession supply vendors). It wouldn't be for just those 2 NPCs.

**Pull request closed without merging**
