### PR TITLE
Quest item drops corrections, updates and cleanups (Part 1)

### PR DESCRIPTION
**Pull request by Exodius**
Corrections to quest item drops to reflect their drop rate from Armory.
Deeper investigation on some items and removal of same from drop tables in/after 4.0.3a
Some of the queries are removing certain items completely from creature_loot_template and some of you (those that don't know) need Safe Mode disabled.
Edit -> Preferences -> SQL Queries -> Uncheck "Safe Updates"

Documentation about these queries can be seen in comments.

### CODE REVIEW

**Comment by Dekadencee** [comment]
Thanks Exodius ^^

**Comment by Exodius** [comment]
For the sake of faster reviewing and because some commits to my branch fucked up this PR, I'll close this one down and split all "issues" from the PR into separate Issue Reports.

Sorry for the inconvenience...

**Comment by Exodius** [comment]
So... Because of the reasons explained in my previous post, I have split everything into Issue Reports. Now, if there are any mistakes or fuckups from my side, they can be easily edited and I can avoid this clusterfuck with PRs...

I have expanded some Queries. It took me a while to track and research everything down but I managed to include Quest Disables for quest and chains I found proof that they were disabled/removed from the game...
You can find everything in these reports: #241, #242, #243, #244, #245, #246, #247, #248, #249, #250, #251, #252, #253, #254, #255, #256, #257, #258, #259, #260, #261, #262, #263, #264, #265, #266, #267, #268, #269, #270, #271, #272, #273, #274, #275, #276, #277, #278, #279, #280, #281.

**Comment by DDuarte** [comment]
I'm starting to sync the 3 months old TDB 4.3.4 with TC, once that is done I'll take care of the fixes lying on this issue tracker. Lose no hope!

**Pull request closed without merging**
