### PR TITLE
Update Mining Loot to support Green and Blue gems.

### PR DESCRIPTION
**Pull request by Exodius**
As it turns out, there was only Define for Cata Green Gems without any reference loot for them. This introduces Blue gems as well.
Closes #312

### CODE REVIEW

**Comment by Exodius** [comment]
I made a mess in those issue reports...
Sorry... :)

**Comment by Aokromes** [comment]
Plz, don't edit older sql files unless they can't be applied, no one digs on commits searching if they need to reapply a 3 months old file.

**Comment by Exodius** [comment]
In that case, please fix the mistake made in 71c409312fde63c2fcee8f3d408725ac39878b9a and I will make classic issue report with updates regarding stuff from this PR.

Define 12906 needs to be changed to 12907.

**Comment by Exodius** [comment]
I'm afraid to place another number after the hashtag... You have a query in issue 312.
I hope I made it properly.

**Pull request closed without merging**
