### PR TITLE
Added missing spell target position for Wrap of Unity Item

### PR DESCRIPTION
**Pull request by ghost**
When using these items will now teleport you to stormwind or ogrimmar.

Item: http://www.wowhead.com/item=63206 -> Spell: http://www.wowhead.com/spell=89157
Item: http://www.wowhead.com/item=63207 -> Spell: http://www.wowhead.com/spell=89158

Added target position for them in spell_target_position

---

Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.0.1c 10 May 2012 (library: OpenSSL 1.0.1c 10 May 2012)
Using ACE version: 6.1.4
TrinityCore rev. 4b4199d75b59 2013-03-04 23:44:25 +0100 (4.3.4 branch) (Win32, Release) (worldserver-daemon)

Realm running as realm ID 1
Using World DB: TDB 434.04

### CODE REVIEW

**Comment by Kinzcool** [comment]
These coords aren't right, I'll have to look in sniffs to get the good coords. We could add "random" positions for all spells that have a target 17 (TARGET_DEST_DB), but we can have the good ones in sniffs, but thanks for the catch.

Oh, and you can make the issue / fix in tracker when its db side :)

**Comment by ghost** [comment]
I used the coords from .tele stormwind and orgrimmar :)

Please provide a link to the which tracker you mean?

**Comment by Kinzcool** [comment]
I mean this tracker : https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/issues

Here's where I've got the positions :

```
ServerToClient: SMSG_SPELL_GO (0x6E16) Length: 59 Time: 06/22/2012 03:48:06.913 Number: 10111
Caster GUID: Full: 0x420000039D9A45F7 Type: Item Low: 15529035255
Caster Unit GUID: Full: 0x0000000000 Type: Player Low: xxx Name: xxx
Cast Count: 104
Spell ID: 89157 (Teleport: Stormwind)
Cast Flags: Unknown4, Unknown7, Unknown16 (262416)
Time: 0
Time2: 307094600
Hit Count: 1
[0] Hit GUID: Full: 0x000000000 Type: Player Low: xxx Name: xxx
Miss Count: 0
Target Flags: Unit, DestinationLocation (66)
Target GUID: 0x0
Destination Transport GUID: 0x0
Destination Position: X: -8998.14 Y: 861.254 Z: 29.6206
Unk Byte 2: 8
```

This one is alliance version, I wasn't the caster, so I don't have the orientation. Then, I can look in SpellEffect.dbc (MoP Version) to got it.

```
ServerToClient: SMSG_SPELL_GO (0x0C8D) Length: 61 ConnectionIndex: 2 Time: 03/05/2013 18:53:58.078 Number: 1857
Caster GUID: Full: 0x45800002B3BCC6C3 Type: 1032 Low: 3015493315
Caster Unit GUID: Full: xxxxxx Type: 8 Low: xxxxxx Name: xxxxxx
Cast Count: 3
Spell ID: 89158 (Teleport: Orgrimmar)
Cast Flags: Unknown4, Unknown7, Unknown8, Unknown16 (262928)
Time: 0
Time2: 1004990216
Hit Count: 1
[0] Hit GUID: Full: xxxxxx Type: 8 Low: xxxxxx Name: xxxxxx
Miss Count: 0
Target Flags: Unit, DestinationLocation (66)
Target GUID: 0x0
Destination Transport GUID: 0x0
Destination Position: X: 1776.5 Y: -4338.8 Z: -7.48
Unk Byte 2: 2

ServerToClient: SMSG_NEW_WORLD (0x081D) Length: 20 ConnectionIndex: 2 Time: 03/05/2013 18:53:59.406 Number: 1880
Map: 1 (Kalimdor)
Y: -4338.8
Orientation: 3.55349
X: 1776.5
Z: -7.48
```

And this one is the horde version, this time, the person who sniffed it was the caster. So, you got an other packet with the orientation, which is SMSG_NEW_WORLD.

**Comment by ghost** [comment]
Oh great Kinzcool used on full debug right?

**Comment by Paradox** [comment]
lol

**Comment by Vincent-Michael** [comment]
@ak47sigh we use sniffs or dbc

**Pull request closed without merging**
